# Generated by Django 4.2.7 on 2024-04-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ROOM_TYPES',
            fields=[
                ('type_rooms', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(verbose_name='Check-in Date')),
                ('checkout_date', models.DateField(verbose_name='Check-out Date')),
                ('num_guests', models.IntegerField(default=1, verbose_name='Number of Guests')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('is_reserved', models.BooleanField(default=False, verbose_name='Is Reserved')),
                ('Room_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.room_types')),
            ],
        ),
    ]
