# Generated by Django 4.2.7 on 2024-05-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
